pr:
- master

queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

# Unit tests only
- task: Npm@1
  displayName: 'unit tests'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test:unit'

# Stand a dockerized MongoDB instance
- task: Docker@1
  displayName: 'Run MongoDB on Docker'
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'Run an image'
    imageName: 'mongo:4.0'
    qualifyImageName: false
    containerName: 'mongo_4_0'
    ports: '27017:27017'
    memoryLimit: 1GB

# Integration tests only
- task: Npm@1
  displayName: 'integration tests'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test:integration'

 # Copy package.json into lib
- task: CopyFiles@1
  displayName: 'Copy package.json to lib'
  inputs:
    contents: 'lib/**'
    targetFolder: 'package'

# Copy package.json into lib
- task: CopyFiles@2
  displayName: 'Copy package.json to lib'
  inputs:
    Contents: 'package.json'
    TargetFolder: 'package'

# Copy readme.md into lib
- task: CopyFiles@2
  displayName: 'Copy readme.md to lib'
  inputs:
    Contents: 'README.md'
    TargetFolder: 'package'

# Publish
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: MongoDbStorage'
  inputs:
    PathtoPublish: package
    ArtifactName: MongoDbStoragePackage



